sudo: required
dist: trusty
services:
- docker
env:
  global:
    secure: aYAE22e5yapGVqIdGCO2PjepBCzXcyoQuhfmjETlrZ3Z9KVvon1/+fNWAvZgAcc9mik3mgG5VWHJwEA32bhFvFpmUpeOx8wVwl4owHGP7xTspfQeFF2Xs0xyXb9dW9xBrZWXCUEWD6+X0hgmgNlS1GSom3b7MMguGkc9JKEPCgMeRab9NWRtCM9jts9iMsNH8YmCp3LLShu5wvwh4CVgdCVvdsMN53D0IvyPNbWoxqQXknLT/FQFVyUXr67smuiu3Wlnsw/+sTddxBElJXuB29ZB29qCm/qHIJdoSUbW16IbtKQMrbbWcg0GG6+XjXY3d0VNnSoIOzLWeJGaOI8pPaANoqampHqMBS/n/MGYrjvvVUCuJ/qfygD1tAIMXvgZP3f4rtdR2eHFqjySXBRkR6SmG6clqar/Vyimod+FjrHJnCBexH17f4/TcO7zcWsFxN7x0y5wXcgkdzK14ZPr7+WQ1H9N+j1tu2qdvabnfsDP4ge0yXnZseQFGWwp3IOJ1O6EhzzCtlkQ6hlA1OxKpBdOe5ql7jvm4dSGBW0uGrmSMYnH9YD8/IDoxOzhZxtq9G32RrOyOwJADb9x7+U1zLBfUDTV/vpjDG/hcUZtCmTM9qjURK1+vRVT6y5px8xpLv0dY6+pqgzZBPosXsNHIG7v+092rJIl2UlKHZex/Dw=
script:
- sudo docker build -t henrywangxf/fedora:latest .
after_success:
- |
  sudo docker tag henrywangxf/fedora:latest henrywangxf/fedora:$TRAVIS_BUILD_NUMBER
  sudo docker push henrywangxf/fedora
notifications:
  email:
    on_failure: change
    on_success: never
