sudo: required
dist: trusty
services:
- docker
env:
  global:
    secure: "y9HFEBMYcSvSbC+HlzczuA3k22WNOEqGQ9+NTMnm+4MGsI+TZaPWAx4qCQ0jovGwJFmyjC2XiAeFopegs3asmaYnzhXwh1YLz7AYTs5SNfwXX2Y+vXSedYXjkVC3vwt6c6nknPdlHslmNDF6t6JPpEMx8ZE7+Fk6g1V/4hxKJ8bfLW/OfxO9yO1S0IUkZjkFSUxKoACIYOtp29MCKBfyCHucn9YSSGE1shnmtmnnUZ70Sa0M+CYWaZ+czqyZ+h9TpkK7WFC1akcAnWkJfZdy3m1GxW5ss50Qy9u381DWrJBAbFvi2RfEetPFmwg1Y4IV9Fr2m5d2lbDE7mmDqd9ACmTr9PhWVEhexeVke0nrWro3MbWGgCMT/HqNqR7gkerXN+jZGK2w7MF+HFJV6+5g5UEbdGn+PSO6H4ACQEL3BYJ2lacuXswR/lrqQd5sVeseUWhtsvfzVFHo9dCW7FlqjqwX9hJBd0LquQ1vJUI+HdOI755VxolQy7FdASthffkN8CZ9vG86ucfdHEes2kesHjTYfWYQAaXUMA8qpdo3YuvTRum9T29cCBCI7MhiDMx8yIW6qeznGPxxcYX22ntepceCFZgWI8xjipN92p+TbavBlZp/vmm5BwKViWBGn0gy0izahCs+aGFn5HAzAd84vyM4Y1S3Bg+aPurBs0ylpoI="
script:
- |
      sudo docker build -t henrywangxf/fedora:latest .
after_success:
- |
      sudo docker login -u henrywangxf -p $DOCKER_PASSWORD
      sudo docker tag henrywangxf/fedora:latest henrywangxf/fedora:$TRAVIS_BUILD_NUMBER
      sudo docker push henrywangxf/fedora
notifications:
  email:
    on_failure: change
    on_success: never
